sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env: VERSION=6
  - os: linux
    dist: trusty
    env: VERSION=7
  - os: osx
    osx_image: xcode9.2
    language: generic
global:
  env:
  - PROJECT=Boost
  - PROJECT_TEMPLATE=default
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition Boost
notifications:
  slack:
    secure: vsT/i9uW3WSUaJeZJbLKP0aW5MnvKUAcmC7IFZM8c8k5A4fkZfPmUINKQkK5+Ec1KKBgmn1abRYEbGI5wLZ+L/uuF3ptdGAVng5LazmDGSiQjM50lwhLPD3JOF6xIYYtRplf2gXtUjZaYxT1g9Nshz7kFtYaB0JnhSNVkMJQsBmH2QO4DaGddxZWbByeeHhllhNM8V7FiliEN+1QVdIr7g8d5n2z9TIkeN022vqnvipzFo1qTZQw0c6e87K0KFB2YXbLftpYZlEVpWs5h8nSLtW12Y0TbA2Y8BtL4kTvMjWUKzKLcviGCae8ICnxHHwrvYlZqFqK7gMYztvU8nTOzWXtY6e2vnsAh1sWZMIwBZQQTHO4KGsAnOIsfeLFg13n/wSO/s75E9HD/iuymPMT6GF17wFj0tKrZEfvOC1TVoZgnZSjieNdZOtKJvsxqBJZVtAvxu6+aFwJ+5EIv9OlAhD0iHxYVgR/pKZH4OWVeq7TgrLtKoR/qF6gV7mF+MHRSTUSQMJU7myxZZ7opbcVbo1uoFcb9ZQhDm2Czvsi2kjt4sKOUMQw7zz7iXkjQEYlqxe0SMnsZDTOU8nsA5hUcX4VUZt3SiXJQRSgkWiF3sczoV6N8q/glwN+ct3fdERoLUW16MgdDf/rjnsWvTPmzaCA+ADm+Lcr3YXszJlEjS8=
